name: Build WCT26NoBadge Deb
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build Tweak
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Theos & Dependencies
        run: |
          brew install ldid xz
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV
          curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
          unzip master.zip -d $HOME/theos/sdks
          mv $HOME/theos/sdks/sdks-master/*.sdk $HOME/theos/sdks/
          rm -rf master.zip $HOME/theos/sdks/sdks-master

      - name: Build Deb Package
        run: make package FINALPACKAGE=1

      - name: Upload Deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WCT26NoBadge-v1.0-1.deb
          path: ./packages/*.deb
